// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Y1YuLSMsoAjMOKqlgKVrpQgDvzKyIV4',
    appId: '1:421930637943:web:7d6a854e8d0a7a5edd4472',
    messagingSenderId: '421930637943',
    projectId: 'service-e8c99',
    authDomain: 'service-e8c99.firebaseapp.com',
    storageBucket: 'service-e8c99.firebasestorage.app',
    measurementId: 'G-RC631XSJV4',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAblRvto7avMEsDmdU1s8hNcs0uHmJ8cQE',
    appId: '1:421930637943:android:6392f0224f5c7fffdd4472',
    messagingSenderId: '421930637943',
    projectId: 'service-e8c99',
    storageBucket: 'service-e8c99.firebasestorage.app',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPn4rezLfMUkvUcKAWBSKag6bFOXlX2qE',
    appId: '1:421930637943:ios:88a81555489c3627dd4472',
    messagingSenderId: '421930637943',
    projectId: 'service-e8c99',
    storageBucket: 'service-e8c99.firebasestorage.app',
    iosBundleId: 'com.example.service',
  );

  static  FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPn4rezLfMUkvUcKAWBSKag6bFOXlX2qE',
    appId: '1:421930637943:ios:88a81555489c3627dd4472',
    messagingSenderId: '421930637943',
    projectId: 'service-e8c99',
    storageBucket: 'service-e8c99.firebasestorage.app',
    iosBundleId: 'com.example.service',
  );
}
